baseURL = 'https://help.snikket.org/'
languageCode = 'en-us'
title = 'Snikket Help'

theme = "ace-documentation"

[params]
site_logo = "/images/snikket-icon.svg"
disableReadmoreNav = true
custom_css = ["css/snikket_docs.css"]
